### ISSUE TITLE
Recursion parent data naming

### ISSUE THREAD

**Issue by kachnitel** [keboola/juicer#1]
The parent column name in result data is named by the field name of the parent data the recursion loops around. If there's deeper nesting with 2 or more levels with the same column name (eg `id`), only the nearest parent is used, possibly creating an issue with linking results back together between different levels.
# Possible solutions:
### Issues:
- `parent_1_id` looks awkward
- If one level refers to the parent as `1:id` while the other just as `id`, it'll create parent_1_id and parent_id only trackable by going back to the configuration
## 2) Allow & use 'rowId' for each JobConfig if specified, refer to it in placeholders
- Should be the cleanest solution

**Comment by odinuv** [comment]
Neither of the options is backward compatible, this can be solved with reasonable case as described in https://developers.keboola.com/extend/generic-extractor/configuration/config/jobs/children/#deep-job-nesting . That (probably un-intentional) feature is now covered by tests https://github.com/keboola/generic-extractor/commit/bfb38084376b0695700a832ac6f2166a50f84d2b
